"""remove_smaple_table

Revision ID: 019b60d5daad
Revises: 4ea5db5142de
Create Date: 2022-10-20 22:56:29.919639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019b60d5daad'
down_revision = '4ea5db5142de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sample_table_pkey')
    )
    # ### end Alembic commands ###
