version: '3.9'

services:

  mongo:
    image: mongo:6.0.5
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - fast_api_05_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  fast_api_05_mongo_data: